export default {
  'acid pools': 'dark',
  'airless asteroid': 'dark',
  ash: 'secondary',
  barren: 'secondary',
  bogs: 'success',
  canyons: 'warning',
  caves: 'dark',
  cities: 'secondary',
  cityscape: 'secondary',
  cliffs: 'warning',
  desert: 'warning',
  deserts: 'warning',
  fields: 'success',
  forests: 'success',
  'fungus forests': 'success',
  'gas giant': 'warning',
  glaciers: 'info',
  grass: 'success',
  grasslands: 'success',
  'grassy hills': 'success',
  hills: 'success',
  'ice canyons': 'info',
  'ice caves': 'info',
  islands: 'warning',
  jungle: 'success',
  jungles: 'success',
  lakes: 'primary',
  'lava rivers': 'danger',
  mesas: 'warning',
  mountain: 'info',
  'mountain ranges': 'info',
  mountains: 'info',
  ocean: 'primary',
  oceans: 'primary',
  plains: 'success',
  plateaus: 'warning',
  rainforests: 'success',
  reefs: 'primary',
  rivers: 'primary',
  rock: 'secondary',
  'rock arches': 'secondary',
  rocky: 'secondary',
  'rocky canyons': 'secondary',
  'rocky deserts': 'secondary',
  'rocky islands': 'secondary',
  savanna: 'warning',
  savannahs: 'warning',
  savannas: 'warning',
  scrublands: 'success',
  seas: 'primary',
  sinkholes: 'dark',
  swamp: 'success',
  swamps: 'success',
  'toxic cloudsea': 'dark',
  tundra: 'info',
  unknown: 'dark',
  urban: 'secondary',
  valleys: 'success',
  verdant: 'success',
  vines: 'success',
  volcanoes: 'danger',
};
